# Generated by Django 4.2.23 on 2026-06-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight loss'), ('muscle_gain', 'Muscle gain'), ('general_fitness', 'General fitness'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility')], max_length=20),
        ),
    ]
